# Generated by Django 5.1.4 on 2025-01-12 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettermind', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='budget',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='ProfData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionNo', models.IntegerField()),
                ('questionText', models.TextField()),
                ('answer', models.TextField()),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profdata', to='bettermind.prof')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionNo', models.IntegerField()),
                ('questionText', models.TextField()),
                ('answer', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userdata', to='bettermind.user')),
            ],
        ),
    ]
