# Generated by Django 5.1.4 on 2025-01-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettermind', '0002_prof_budget_profdata_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='expertise',
            field=models.CharField(default='', max_length=200),
        ),
    ]
