# Generated by Django 5.1.4 on 2025-01-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettermind', '0003_prof_expertise'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fcm_token',
            field=models.CharField(default='', max_length=200),
        ),
    ]
