# Generated by Django 5.1.4 on 2025-01-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bettermind', '0004_customuser_fcm_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fcm_token',
        ),
        migrations.AddField(
            model_name='prof',
            name='fcm_token',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(default='', max_length=200),
        ),
    ]
